Projet/urls.py
from django.contrib import admin
from django.urls import path
from appenv import views
from appenv import api_views
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path("admin/", admin.site.urls, name="admin"),
    path('login/', views.login_view, name="login"),
    path('dashboard/', views.dashboard_view, name="dashboard"),
    path('temperature/', views.temperature_view, name="temperature"),
    path('humidity/', views.humidity_view, name="humidity"),
    path("devices/", views.devices_view, name="devices"),
    path("logout/", views.logout_view, name="logout"),

    path("add_device/", views.add_device, name="add_device"),

    path('get_device_info/<int:id_device>/', views.get_device_info, name='get_device_info'),
    path('get_all_devices_info/', views.get_all_devices_info, name='get_all_devices_info'),

    path('change_device_status/<int:id_device>/', views.change_device_status, name='change_device_status'),
    path('delete_device/<int:id_device>/', views.delete_device, name='delete_device'),

    # REST API
    path('hello/', api_views.HelloView.as_view(), name='hello'),
    path('get_device/', api_views.GetDeviceView.as_view(), name='get_device'),
    path('get_current_temperature/', api_views.GetCurrentTemperature.as_view(), name='get_current_temperature'),
    path('get_current_humidity/', api_views.GetCurrentHumidity.as_view(), name='get_current_humidity'),
    path('get_temperature_30min/', api_views.GetTemperature30min.as_view(), name='get_temperature_30min'),
    path('get_humidity_30min/', api_views.GetHumidity30min.as_view(), name='get_humidity_30min'),
    path('get_temperature_1day/', api_views.GetTemperature1day.as_view(), name='get_humidity_1day'),
    path('get_humidity_1day/', api_views.GetHumidity1day.as_view(), name='get_humidity_1day'),

]

appenv/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
# from djongo import models
# from pynamodb.models import Model
from django.db.models.deletion import CASCADE


class Device(models.Model):
    device_id = models.PositiveIntegerField(primary_key=True)
    device_name = models.CharField(max_length=50)
    # device_type = models.IntegerField()
    TYPE_CHOICES = [
        (11, 'dht11'),
    ]
    device_type = models.IntegerField(choices=TYPE_CHOICES)
    gpio = models.PositiveIntegerField()
    active = models.BooleanField(null=True, default=True)


class Temperature(models.Model):
    device = models.ForeignKey(Device, on_delete=CASCADE, null=False)
    temperature = models.FloatField()
    sample_time = models.DateTimeField(auto_now_add=True)


class Humidity(models.Model):
    device = models.ForeignKey(Device, on_delete=CASCADE, null=False)
    humidity = models.FloatField()
    sample_time = models.DateTimeField(auto_now_add=True)

templates/home/addDevice.html
{% extends "layouts/base.html" %}

{% block title %} Add a device {% endblock %}


{% block content %}

    <h1>Devices</h1>
    <hr><br>

    <h2>Add a device</h2>
    <br>
    <div class='form'>
        <div class='form_device'>
            <form action="#" method="POST">
                {% csrf_token %}
                <p>Device ID:</p>
                {{ device_form.device_id }}<br>
                <p>Device name:</p>
                {{ device_form.device_name }}<br>
                <p>Device type:</p>
                {{ device_form.device_type }}<br>
                <p>GPIO port:</p>
                {{ device_form.gpio }}<br>
                <p>Active device:</p>
                {{ device_form.active }}<br><br>
                <button type="submit" name='submit_device' class="button">
                    Confirm
                </button>
                <br><br>
            </form>

        </div>
    </div>

{% endblock content %}

templates/home/dashboard.html
{% extends "layouts/base.html" %}
{% load static %}
{% load tags %}
{% block title %} Dashboard {% endblock %}


{% block content %}

    <h1>Dashboard</h1>
    <hr><br>
    {% for d in dashboard_data %}
        {% if d|get_value:'is_active' == True %}
            {% with id=d|get_value:'device_id' %}
                <h2><i class="fa fa-toggle-on" style="color: #67b168;"></i> Sensor "{{ d|get_value:'device_name' }}" is
                    active</h2>
                <h4 id="last-update-time-{{ id }}">Last update time: {{ d|get_value:'last_update_time' }}</h4>

                <div class="row">
                    <div class="col" style="padding-right: 1.5em">
                        <h3>Current temperature</h3>
                        <div id="chart-current-temperature-{{ id }}" class="chart chart-gauge"></div>
                    </div>

                    <div class="col">
                        <h3>Current humidity</h3>
                        <div id="chart-current-humidity-{{ id }}" class="chart chart-gauge"></div>
                    </div>
                </div>

                <script>

                    const baseURL = location.protocol + '//' + location.hostname + (location.port ? ':' + location.port : '');;
                    const token = 'xxxxxxxxxx';

                    // Current temperature gauge
                    var chartDom_current_temperature_{{ id }} = document.getElementById('chart-current-temperature-{{ id }}');
                    var myChart_current_temperature_{{ id }} = echarts.init(chartDom_current_temperature_{{ id }});
                    var option_current_temperature_{{ id }};

                    option_current_temperature_{{ id }} = {

                        textStyle: {
                            fontStyle: 'normal',
                            fontWeight: 'normal',
                            fontFamily: 'Open Sans',
                            fontSize: 12,
                        },
                        series: [
                            {
                                type: 'gauge',
                                center: ['50%', '60%'],
                                startAngle: 200,
                                endAngle: -20,
                                min: -5,
                                max: 40,
                                splitNumber: 9,
                                itemStyle: {
                                    color: '#599dc7'
                                },
                                progress: {
                                    show: true,
                                    width: 30
                                },
                                pointer: {
                                    show: false
                                },
                                axisLine: {
                                    lineStyle: {
                                        width: 30
                                    }
                                },
                                axisTick: {
                                    distance: -45,
                                    splitNumber: 5,
                                    lineStyle: {
                                        width: 1,
                                    }
                                },
                                splitLine: {
                                    distance: -52,
                                    length: 14,
                                    lineStyle: {
                                        width: 3,
                                    }
                                },
                                axisLabel: {
                                    distance: -20,
                                    fontSize: 18
                                },
                                anchor: {
                                    show: false
                                },
                                title: {
                                    show: false
                                },
                                detail: {
                                    valueAnimation: true,
                                    width: '60%',
                                    lineHeight: 40,
                                    borderRadius: 8,
                                    offsetCenter: [0, '-15%'],
                                    fontSize: 45,
                                    fontWeight: 'bolder',
                                    formatter: '{value} °C',
                                    color: 'auto'
                                },
                                data: [
                                    {
                                        value: {{ d|get_value:'current_temperature' }}
                                    }
                                ]
                            },
                        ]
                    };
                    myChart_current_temperature_{{ id }}.setOption(option_current_temperature_{{ id }});

                    // Current humidity gauge
                    var chartDom_current_humidity_{{ id }} = document.getElementById('chart-current-humidity-{{ id }}');
                    var myChart_current_humidity_{{ id }} = echarts.init(chartDom_current_humidity_{{ id }});
                    var option_current_humidity_{{ id }};

                    option_current_humidity_{{ id }} = {

                        textStyle: {
                            fontStyle: 'normal',
                            fontWeight: 'normal',
                            fontFamily: 'Open Sans',
                            fontSize: 12,
                        },
                        series: [
                            {
                                type: 'gauge',
                                center: ['50%', '60%'],
                                startAngle: 200,
                                endAngle: -20,
                                min: 0,
                                max: 100,
                                splitNumber: 10,
                                itemStyle: {
                                    color: '#59c780'
                                },
                                progress: {
                                    show: true,
                                    width: 30
                                },
                                pointer: {
                                    show: false
                                },
                                axisLine: {
                                    lineStyle: {
                                        width: 30
                                    }
                                },
                                axisTick: {
                                    distance: -45,
                                    splitNumber: 5,
                                    lineStyle: {
                                        width: 1,
                                    }
                                },
                                splitLine: {
                                    distance: -52,
                                    length: 14,
                                    lineStyle: {
                                        width: 3,
                                    }
                                },
                                axisLabel: {
                                    distance: -20,
                                    fontSize: 18
                                },
                                anchor: {
                                    show: false
                                },
                                title: {
                                    show: false
                                },
                                detail: {
                                    valueAnimation: true,
                                    width: '60%',
                                    lineHeight: 40,
                                    borderRadius: 8,
                                    offsetCenter: [0, '-15%'],
                                    fontSize: 45,
                                    fontWeight: 'bolder',
                                    formatter: '{value} %',
                                    color: 'auto'
                                },
                                data: [
                                    {
                                        value: {{ d|get_value:'current_humidity' }}
                                    }
                                ]
                            },
                        ]
                    };
                    myChart_current_humidity_{{ id }}.setOption(option_current_humidity_{{ id }});


                    setInterval(function () {
                        // get current temperature
                        $.ajax({
                            url: baseURL + '/get_current_temperature/?id_device={{ id }}',
                            headers: {Authorization: 'Token ' + token},
                            method: 'GET',
                            contentType: "application/json",
                            beforeSend: function () {
                            },
                            success: function (data) {
                                myChart_current_temperature_{{ id }}.setOption({
                                    series: [
                                        {
                                            data: [
                                                {
                                                    value: data["temperature"]
                                                }
                                            ]
                                        },

                                    ]
                                });

                                // Parse the timestamp as a Date object
                                const timestamp = data["sample_time"];
                                const date = new Date(timestamp);

                                // Use toLocaleDateString and toLocaleTimeString to format the Date object as a string
                                const formattedDate = date.toLocaleDateString("fr-FR");  // Output: "12/29/2022"
                                const formattedTime = date.toLocaleTimeString("fr-FR");  // Output: "8:11:38 PM"

                                // Concatenate the formatted date and time to get the final result
                                const formattedTimestamp = `${formattedDate} ${formattedTime}`;

                                $('#last-update-time-{{ id }}').text('Last update time: ' + formattedTimestamp)
                            },
                            error: function (jqXHR, ex) {
                                alert("Error")
                            }
                        })

                        // get current humidity
                        $.ajax({
                            url: baseURL + '/get_current_humidity/?id_device={{ id }}',
                            headers: {Authorization: 'Token ' + token},
                            method: 'GET',
                            contentType: "application/json",
                            beforeSend: function () {
                            },
                            success: function (data) {
                                myChart_current_humidity_{{ id }}.setOption({
                                    series: [
                                        {
                                            data: [
                                                {
                                                    value: data["humidity"]
                                                }
                                            ]
                                        },

                                    ]
                                });
                            },
                            error: function (jqXHR, ex) {
                                alert("Error")
                            }
                        })
                    }, 1000);

                </script>
            {% endwith %}

        {% else %}
            <h2><i class="fa fa-toggle-off" style="color: #a94442;"></i> Sensor "{{ d|get_value:'device_name' }}" is
                disabled</h2>
        {% endif %}
        <hr><br>
    {% endfor %}

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

{% endblock javascripts %}

templates/home/devices.html
{% extends "layouts/base.html" %}
{% load auth_extras %}
{% block title %} Devices {% endblock %}


{% block content %}

    <h1>Devices</h1>
    <hr><br>

    {% for message in messages %}
        {% if message.tags == "success" %}
            <div class="alert alert-success animated fadeInDown">
        {% elif message.tags == "error" %}
            <div class="alert alert-error animated fadeInDown">
        {% elif message.tags == "warning" %}
            <div class="alert alert-warning animated fadeInDown">
        {% else %}
            <div class="alert alert-danger animated fadeInDown">
        {% endif %}
        <a class="close" href="#" data-dismiss="alert" style="margin-left: 0.5em; color: #000000; text-decoration: none;">×</a>
        {{ message }}
        </div>
        <br>
    {% endfor %}
    {% if request.user|has_group:"admin" %}
        <div class="button">
            <a href="{% url 'add_device' %}"><i class="fa fa-plus" style="color: white; padding-right: 1rem"></i>Add a device</a>
        </div><br>
    {% endif %}

<div id="tableDevice">
    <table class="table">
        <tr class="title">
            <th>ID</th>
            <th>Name</th>
            <th>Type</th>
            <th>GPIO</th>
            <th>Status</th>
            {% if request.user|has_group:"admin" %}
                <th>Action</th>
            {% endif %}
        </tr>

        {% for d in devices %}
            <tr>
                <td>{{ d.device_id }}</td>
                <td>{{ d.device_name }}</td>
                <td>{{ d.get_device_type_display }}</td>
                <td>{{ d.gpio }}</td>
                {% if d.active == True %}
                    <td>
                        <button class="toggle-btn" value="{{ d.device_id }}">
                            <div class="toggle-div toggle-div-on"><i
                                    class="fa fa-toggle-on nav-icons toggle-icon toggle-icon-on"
                                    style="color: #67b168;"></i></div>
                            <div class="toggle-div toggle-div-off" hidden><i
                                    class="fa fa-toggle-off nav-icons toggle-icon toggle-icon-off"
                                    style="color: #a94442;" hidden></i></div>
                        </button>
                    </td>
                {% else %}
                    <td>
                        <button class="toggle-btn" value="{{ d.device_id }}">
                            <div class="toggle-div toggle-div-off"><i
                                    class="fa fa-toggle-off nav-icons toggle-icon toggle-icon-off"
                                    style="color: #a94442;"></i></div>
                            <div class="toggle-div toggle-div-on" hidden><i
                                    class="fa fa-toggle-on nav-icons toggle-icon toggle-icon-on"
                                    style="color: #67b168;"></i></div>
                        </button>
                    </td>
                {% endif %}
                {% if request.user|has_group:"admin" %}
                    <td>
                        <button class="delete-btn" value="{{ d.device_id }}">
                            <a href="{% url 'delete_device' id_device=d.device_id %}"
                               onclick="return confirm('Are you sure you want to delete this?')"
                               style="text-decoration: none">
                                {#                        <a href="#" style="text-decoration: none">#}
                                <i class="fa fa-circle-xmark nav-icons toggle-icon"
                                   style="color: #a94442; font-size: 1.2em;"></i>
                            </a>
                        </button>
                    </td>
                {% endif %}
            </tr>
        {% endfor %}

    </table>
    <br><br>
</div>

<script>

</script>

{% endblock content %}